### ISSUE TITLE
QT

### ISSUE THREAD

**Issue by Otorhin** [salieff/es_mod_installer#1]
Какая версия QT, SDK, NDK использовалась в проекте для сборки?

**Comment by salieff** [comment]
Android для armeabi-v7a (GCC 4.9, Qt 5.7.1)
Android для x86 (GCC 4.9, Qt 5.7.1)

Ставилось целиком бандлом с сайта Qt

>Среда, 18 апреля 2018, 18:33 +03:00 от Otorhin <notifications@github.com>:
>
>Какая версия QT, SDK, NDK использовалась в проекте для сборки?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Alexander Salieff
salieff@mail.ru

**Comment by Otorhin** [comment]
Последний вопрос. А под чем собиралось? Windows/Linux?

**Comment by salieff** [comment]
Я собирал под Linux, но, по идее, разницы быть не должно
